#To Do
* ~~Login - Authenticate~~

* Read court that needs to be booked
* ~~Map "human" court selection to website~~

* ~~Navigate to two weeks for the day (day could be flexible in later models?)~~

* ~~Identify court to book (What link to book?!)~~
* ~~Identify pattern court id, `ctid`. Can it be calculated, or derived?~~
* ~~Move court numbers from `Main.R` to a seperate sheet. Are they even needed?~~
* Create login function.
* Create login function tests
* Devise way of entering court required. Or even a vector of required courts!
* Investigate methods to run this program at 7am when needed.
* Send text alerts when a court is successfully booked? (and warnings when not?!)


#The Process

##Motivation

I like squash. Mycourts is a court booking system. It allows you to log in through an account book courts. Depending on where you play, this can be quite competitive process. Courts are available to book up to 14 days in advance at 7am on the day. I'd often forget to book these, so I wanted a way to set it and forget it!

## A proof of concept

My first goal was to walk through the process of booking a court using just `R`. This took me three days when I had spare moments. Despite using the system frequently, I had no clue how it operated behind the UI, so a lot of this time was spent exploring the system and improving my knowledge of `httr` and `rvest`.
I started Monday morning on the train to Birmingam.
Navigating to mycourts.co.uk was easy enough. My first real hurdle was logging in.

By Tuesday morning I had successfully logged in through R. Along the way I has learnt a bit about sessions, forms and CSS selectors (I was going to learn even more on these very soon).

The next challenge was navigating to the day. For ease of having a court that no one else would book, I chose 14 days away. Mycourts makes this easy, as the dates are relative to today's date, so the url for 14 days away is always the same.

After that, I had to select the court desired. The core of this is finding following the "book this court" link for the desired court. As this was a proof of concept, I already knew what court I wanted, so the challenge here was just identifying the correct link and following it.


Finally, once I had found followed the "book this court" link, it takes you to a final confirmation page. This was another round of learning css selectors so that I could narrow down the correct link to follow.

SUCCESS! I had booked a court through `R`.

Along the way, I realised that in fact some of this was not neccessary. Rather than having to narrow down which court I want and select that link, I realise there was a general stucture to the booking hyperlinks. I could instead construct the hyperlink for the court that I wanted! 
###Thursday

There are two ways I could "find" the link for the court I wish to book. The key components of the link are the `ctid` (court id) and the date. The date is easy enough to compute, I know which day I want to play ;)

The court id is a bit trickier. This is a 5 digit number that represents a particular court at a particular time. After investigation, it appears that this number is the same across different days/months, and references purely a court and time. This makes sense, as otherwise the date would not be needed when constructing the query.

As the court id is the same, It would be possible to create a giant mapping of court/time to court id. However, this is labour intensive (which I'm not a fan of), and wouldn't generalise well to other mycourt systems as the id's will be different!

An alternative could be to make a slightly more generalised mapping, as the id of the court/time can be calculated if you know how many court slots are available in a day. This is a lot quicker to do, and would generalise more easily.

A second alternative would be to create a function that would take a time and court (or if advanced, just a time), and parse the webpage to find a suitable court id. Once found, this court id could be extracted to construct the correct hyperlink. This would generalise to any club (as long as MyCourt's doesn't change..)

###Friday

I realised that the two step confirmation process for the courts is not actually needed for booking a court. Following the hyperlink for "confirming" a booking will book the court regardless of any previous steps (as long as you're logged in). This means that rather than choosing a court with one hyperlink, then confirming it with another, I can book courts by assembling just one hyperlink and following it.

### Tuesday

I created the first iteration of the function I described on Thursday, that takes a desired time and court and returns the `ctid` for the desired court. Once extracted, the URL to book the court can be constructed.

###Wednesday

Worked further on wrapper function to take court selection and return link that will book court. Needs some safety features though (ie "this court is already booked", "time not found", "court not found" etc)
